In [1]:
import cv2

In [2]:
image = cv2.imread("C:\\Users\\RJ\\Desktop\\Coding Circle\\Web Design and Development\\HTML College\\bmw.png", 1)

In [3]:
#in above ,1 is for color image. The image is converted into numpy 3d array
print(image)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [4]:
#type of it
print(type(image))

<class 'numpy.ndarray'>


In [5]:
#size of the image
print(image.shape) #in color image you will know there 3 which is for RGB and there are 668 rows and 670 columns

(668, 670, 3)


In [6]:
cv2.namedWindow('car', cv2.WINDOW_NORMAL)
cv2.imshow('car',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
#to see image on screen first. 
# we need write the above code the car is title of image and waitkey is zero and when you click zero then it will be closed
#now remove the first line then run and if error is coming or any of thing or image is not showing up
#here is a special case where you can already create a window and load image to it later. 
#In that case, you can specify whether window is resizable or not. 
#It is done with the function cv2.namedWindow(). By default, the flag is cv2.WINDOW_AUTOSIZE.
#But if you specify flag to be cv2.WINDOW_NORMAL, 
#you can resize window. It will be helpful when image is too large in dimension and adding track bar to windows.